name: illgraben
channels:
        - conda-forge

dependencies:
        - python=3.9.*
        - pip=20.*
        - pip:
                - statictypes  # For static type checking/enforcing
                - https://s3-eu-west-1.amazonaws.com/download.agisoft.com/Metashape-1.7.1-cp35.cp36.cp37.cp38-abi3-linux_x86_64.whl

