name: illgraben
channels:
        - conda-forge

dependencies:
        - python=3.9
        - pip
        - pip:
                - https://s3-eu-west-1.amazonaws.com/download.agisoft.com/Metashape-1.7.2-cp35.cp36.cp37.cp38-abi3-linux_x86_64.whl

